### ISSUE TITLE
Using readsb API

### ISSUE THREAD

**Issue by om3wuc** [RundesBalli/adsbTelegramNotifier#1]
Using readsb api (--net-api-port 8042) as source of the data would be more useful for setting below altitude + above altitude,  or box instead of circle...  For logging planes to csv (airport area) I'm using api: 
`http://<ip>:8042/?box=<lat south>,<lat north>,<lon west>,<lon east>&above_alt_baro=1&below_alt_baro=6000 `

**Comment by RundesBalli** [comment]
Hello,

thank you for your suggestion, but I would like to politely decline. I will explain why below.

Most users use the default configuration of readsb. Many of them simply don't have the interest to get into the configurations so far that the API runs properly. I have received several requests from users in the meantime, despite the - in my opinion good - documentation of this notifier, whether they have set up the notifier correctly, just to make sure that everything works properly.

Therefore, I assume that a large part of the users are simply users and not configuration athletes, who want the simplest possible setup without a lot of bells and whistles.

Anyway, I discovered through your issue that there was the minAlt option, but I didn't develop any processing of that option in the notifier, which I made up for in the commit f0c086ca4f69ff914aef277a556f859d66666590, 52c2d22929cf7ee01b468b8facead65e9f3cd38d and cdea204ab4f51d5bcb7114384015a6fec8be3927. Thanks for that!

// Edit: I added a maxAlt option for you in the above commits. Maybe this is helpful for you.

RundesBalli
